### ISSUE TITLE
Wrong lyrics

### ISSUE THREAD

**Issue by DonB7** [ChenghaoMou/touchbar-lyric#17]
Hey,
The project overall is very cool, On some songs it works perfectly, but in about 50% the lyrics are from another song. I am using spotify. Thank you a lot for solution. I dont know what version I have. I used the json file here on the page.
Kind regard and thanks a lot for any solution.

**Comment by DonB7** [comment]
I used this tutorial - https://www.youtube.com/watch?v=IL2H7zu5Yq4

**Comment by ChenghaoMou** [comment]
Hi, you can upgrade this by running the following command in your terminal:
```
pip3 install touchbar_lyric --upgrade
```

If you can provide some songs with wrong lyrics here, I can take a look to see if there is anything I can do to fix it.

**Comment by DonB7** [comment]
I tried, but It did not work. I am having issues even with the most favorite ones like Jorja Smith - Addicted, AJ Tracey - Dinner guest and more. The lyrics are perfectly sinced on spotify, but not in the touch bar.

**Comment by ChenghaoMou** [comment]
Thanks for the feedback. I have updated this tool and increased the search parameters, so it should give you better coverage now. I tested it with the two songs you mentioned, it should work.

After you upgrade the tool by 
```
pip3 install touchbar_lyric --upgrade
```
you should also clean the lyric cache by running this command as well:
```bash
rm -rf ~/.cache/00{0,1,2,3,4,5,6,7}
```

Regarding the delay, it is inevitable since it is retrieving and parsing lyrics on the fly from two Chinese companies and I have no say in the lyric quality either :(

**Comment by ChenghaoMou** [comment]
I am going to close this assuming the last fix should solve the issue. You are welcome to open another one if anything comes up.
